cp media/rdf-kern.graphml libs/rdf-kern.graphml
cp media/rdf-relatiekern.graphml libs/rdf-relatiekern.graphml
cp media/rdf-datatype.graphml libs/rdf-datatype.graphml
cp media/rdf-constraint.graphml libs/rdf-constraint.graphml
cp media/rdf-keuze-datatype.graphml libs/rdf-keuze-datatype.graphml
cp media/rdf-keuze-attribuut.graphml libs/rdf-keuze-attribuut.graphml
cp media/rdf-keuze-relatiedoel.graphml libs/rdf-keuze-relatiedoel.graphml
cp media/rdf-keuze-relatiesoort.graphml libs/rdf-keuze-relatiesoort.graphml
cp media/rdf-relatie.graphml libs/rdf-relatie.graphml
cp media/rdf-packages.graphml libs/rdf-packages.graphml
